### PR TITLE
Closes #163 - Switching to fmt.Errorf

### LINKED ISSUE #163: Not using fmt.Errorf everywhere
Golint doesn't like using `fmt.Sprintf` inside `errors.New`, and while many of those `errors.New` might be from gone instead of native, there wouldn't be any significant advantage to using gone errors if they are being constructed based on the output of `fmt.Sprintf` anyway, so may as well just use `fmt.Errorf` like it wants.

### PR DESCRIPTION
**Pull request by proidiot**
Switching a few `errors.New(fmt.Sprintf(...` calls to `fmt.Errorf(...`

### CODE REVIEW

**Comment by loslosbaby** [comment]
Did you find all occurrences of 'unmarsheled'?

**Comment by proidiot** [comment]
@loslosbaby yep! I grepped for it, got all the remaining instances of "unmarshaled" and "Unmarshaled" in all the files that weren't external or uncommitted backups.

To give you a head's up: the standard library interface name `encoding/json.Unmarshaler` just has one "L", probably because somebody misspelled it and then fell back on the whole "name interfaces by adding -er" trope as an excuse. However, that doesn't automatically make using "unmarshaled" right, especially since we are using a different suffix, so I do think correcting it in our codebase is indeed the right move here.

**Comment by loslosbaby** [comment]
Right but I also see “unmarsheled”...with an “e”!!

**Comment by proidiot** [comment]
D'oh! Fixed it now.

It is probably worth automatically running the spellcheck linter in the future.... maybe a dedicated bug report is called for here? *coughcough*

**Pull request merged**
